//! Embedded static resources with content-hash filenames.
//!
//! This module provides a type-safe way to manage embedded assets that need:
//! - Compile-time inclusion via `include_str!`
//! - Content-based hash for cache busting
//! - Optional template variable replacement
//!
//! # Example
//!
//! ```ignore
//! use embed::{EmbeddedAsset, AssetKind};
//!
//! // Define an asset
//! const CSS: EmbeddedAsset = EmbeddedAsset::new(
//!     AssetKind::Css,
//!     "enhance",
//!     include_str!("css/enhance.css"),
//! );
//!
//! // Get filename with hash: ".enhance-a1b2c3d4.css"
//! let filename = CSS.filename();
//!
//! // Write to disk
//! CSS.write_to(&output_dir)?;
//! ```

use std::fs;
use std::path::{Path, PathBuf};

/// Attribute marking tags generated by Tola (not user content).
pub const GENERATED_ATTR: &str = "data-tola-generated";

/// Asset file type, determines extension and MIME type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AssetKind {
    Css,
    JavaScript,
}

impl AssetKind {
    /// File extension for this asset kind.
    pub const fn extension(&self) -> &'static str {
        match self {
            Self::Css => "css",
            Self::JavaScript => "js",
        }
    }

    /// MIME content type for this asset kind.
    pub const fn content_type(&self) -> &'static str {
        match self {
            Self::Css => "text/css; charset=utf-8",
            Self::JavaScript => "application/javascript; charset=utf-8",
        }
    }
}

/// Template variable for replacement in asset content.
#[derive(Debug, Clone, Copy)]
pub enum TemplateVar {
    /// WebSocket port for hot reload: `__TOLA_WS_PORT__`
    WsPort(u16),
}

impl TemplateVar {
    /// Placeholder string in the template.
    pub const fn placeholder(&self) -> &'static str {
        match self {
            Self::WsPort(_) => "__TOLA_WS_PORT__",
        }
    }

    /// Replacement value as string.
    pub fn value(&self) -> String {
        match self {
            Self::WsPort(port) => port.to_string(),
        }
    }
}

/// An embedded static asset with content-hash filename.
#[derive(Debug, Clone)]
pub struct EmbeddedAsset {
    kind: AssetKind,
    name: &'static str,
    content: &'static str,
}

impl EmbeddedAsset {
    /// Create a new embedded asset.
    pub const fn new(kind: AssetKind, name: &'static str, content: &'static str) -> Self {
        Self { kind, name, content }
    }

    /// Compute content hash (8-char hex fingerprint).
    pub fn hash(&self) -> String {
        crate::utils::hash::fingerprint(self.content)
    }

    /// Get the hashed filename: `.{name}-{hash}.{ext}`
    pub fn filename(&self) -> String {
        format!(
            ".{}-{}.{}",
            self.name,
            self.hash(),
            self.kind.extension()
        )
    }

    /// Get the raw content.
    pub fn content(&self) -> &str {
        self.content
    }

    /// Get content with template variables replaced.
    pub fn render(&self, vars: &[TemplateVar]) -> String {
        let mut result = self.content.to_string();
        for var in vars {
            result = result.replace(var.placeholder(), &var.value());
        }
        result
    }

    /// Write asset to output directory.
    ///
    /// Returns the relative path to the written file.
    pub fn write_to(&self, output_dir: &Path) -> std::io::Result<PathBuf> {
        let filename = self.filename();
        let path = output_dir.join(&filename);
        std::fs::write(&path, self.content)?;
        Ok(PathBuf::from(filename))
    }

    /// Write asset with template variables to output directory.
    pub fn write_rendered_to(
        &self,
        output_dir: &Path,
        vars: &[TemplateVar],
    ) -> std::io::Result<PathBuf> {
        let filename = self.filename();
        let path = output_dir.join(&filename);
        fs::write(&path, self.render(vars))?;
        Ok(PathBuf::from(filename))
    }

    /// Clean up old versions of this asset.
    ///
    /// Removes files matching `.{name}-*.{ext}` except current version.
    pub fn cleanup_old(&self, output_dir: &Path) -> std::io::Result<()> {
        let current = self.filename();
        let prefix = format!(".{}-", self.name);
        let suffix = format!(".{}", self.kind.extension());

        for entry in fs::read_dir(output_dir)? {
            let entry = entry?;
            let name = entry.file_name();
            let name_str = name.to_string_lossy();

            if name_str.starts_with(&prefix)
                && name_str.ends_with(&suffix)
                && name_str != current
            {
                fs::remove_file(entry.path())?;
            }
        }

        Ok(())
    }

    /// Generate a `<script>` or `<link>` tag for this asset.
    ///
    /// The tag includes `data-tola-generated` attribute to mark it as
    /// generated by Tola (not user content).
    pub fn html_tag(&self) -> String {
        let filename = self.filename();
        match self.kind {
            AssetKind::Css => format!(
                r#"<link rel="stylesheet" href="/{}" {}>"#,
                filename, GENERATED_ATTR
            ),
            AssetKind::JavaScript => format!(
                r#"<script src="/{}" {}></script>"#,
                filename, GENERATED_ATTR
            ),
        }
    }
}

// ============================================================================
// Predefined Assets
// ============================================================================

/// Enhance CSS for SVG theme adaptation and dark mode.
pub const ENHANCE_CSS: EmbeddedAsset = EmbeddedAsset::new(
    AssetKind::Css,
    "enhance",
    include_str!("css/enhance.css"),
);

/// Hot reload runtime JavaScript.
pub const HOTRELOAD_JS: EmbeddedAsset = EmbeddedAsset::new(
    AssetKind::JavaScript,
    "hotreload",
    include_str!("serve/hotreload.js"),
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_asset_filename() {
        let filename = ENHANCE_CSS.filename();
        assert!(filename.starts_with(".enhance-"));
        assert!(filename.ends_with(".css"));
    }

    #[test]
    fn test_asset_hash_length() {
        let hash = ENHANCE_CSS.hash();
        assert_eq!(hash.len(), 8);
        assert!(hash.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn test_template_render() {
        let js = EmbeddedAsset::new(
            AssetKind::JavaScript,
            "test",
            "connect(__TOLA_WS_PORT__)",
        );
        let rendered = js.render(&[TemplateVar::WsPort(35729)]);
        assert_eq!(rendered, "connect(35729)");
    }

    #[test]
    fn test_html_tag_css() {
        let tag = ENHANCE_CSS.html_tag();
        assert!(tag.starts_with(r#"<link rel="stylesheet" href="/.enhance-"#));
        assert!(tag.contains("data-tola-generated"));
        assert!(tag.ends_with(r#">"#));
    }

    #[test]
    fn test_html_tag_js() {
        let tag = HOTRELOAD_JS.html_tag();
        assert!(tag.starts_with(r#"<script src="/.hotreload-"#));
        assert!(tag.contains("data-tola-generated"));
        assert!(tag.ends_with(r#"></script>"#));
    }
}
