//! Embedded static resources with content-hash filenames.
//!
//! This module provides a type-safe way to manage embedded assets that need:
//! - Compile-time inclusion via `include_str!`
//! - Content-based hash for cache busting
//! - Optional template variable replacement
//!
//! # Example
//!
//! ```ignore
//! use embed::{EmbeddedAsset, AssetKind};
//!
//! // Define an asset
//! const CSS: EmbeddedAsset = EmbeddedAsset::new(
//!     AssetKind::Css,
//!     "enhance",
//!     include_str!("css/enhance.css"),
//! );
//!
//! // Get filename with hash: ".enhance-a1b2c3d4.css"
//! let filename = CSS.filename();
//!
//! // Write to disk
//! CSS.write_to(&output_dir)?;
//! ```

use std::fs;
use std::path::{Path, PathBuf};

/// Attribute marking tags generated by Tola (not user content).
pub const GENERATED_ATTR: &str = "data-tola-generated";

/// Asset file type, determines extension and MIME type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AssetKind {
    Css,
    JavaScript,
}

impl AssetKind {
    /// File extension for this asset kind.
    pub const fn extension(&self) -> &'static str {
        match self {
            Self::Css => "css",
            Self::JavaScript => "js",
        }
    }
}

/// Template variable for replacement in asset content.
#[derive(Debug, Clone, Copy)]
pub enum TemplateVar {
    /// WebSocket port for hot reload: `__TOLA_WS_PORT__`
    WsPort(u16),
}

impl TemplateVar {
    /// Placeholder string in the template.
    pub const fn placeholder(&self) -> &'static str {
        match self {
            Self::WsPort(_) => "__TOLA_WS_PORT__",
        }
    }

    /// Replacement value as string.
    pub fn value(&self) -> String {
        match self {
            Self::WsPort(port) => port.to_string(),
        }
    }
}

/// An embedded static asset with content-hash filename.
#[derive(Debug, Clone)]
pub struct EmbeddedAsset {
    kind: AssetKind,
    name: &'static str,
    content: &'static str,
}

impl EmbeddedAsset {
    /// Create a new embedded asset.
    pub const fn new(kind: AssetKind, name: &'static str, content: &'static str) -> Self {
        Self { kind, name, content }
    }

    /// Compute content hash (8-char hex fingerprint).
    pub fn hash(&self) -> String {
        crate::utils::hash::fingerprint(self.content)
    }

    /// Compute hash of rendered content (with template vars replaced).
    pub fn hash_rendered(&self, vars: &[TemplateVar]) -> String {
        crate::utils::hash::fingerprint(&self.render(vars))
    }

    /// Get the hashed filename: `.{name}-{hash}.{ext}`
    pub fn filename(&self) -> String {
        format!(
            ".{}-{}.{}",
            self.name,
            self.hash(),
            self.kind.extension()
        )
    }

    /// Get hashed filename with rendered content hash.
    /// Use this for assets with template variables to ensure cache-busting
    /// when variable values change (e.g., WebSocket port).
    pub fn filename_rendered(&self, vars: &[TemplateVar]) -> String {
        format!(
            ".{}-{}.{}",
            self.name,
            self.hash_rendered(vars),
            self.kind.extension()
        )
    }

    /// Get content with template variables replaced.
    pub fn render(&self, vars: &[TemplateVar]) -> String {
        let mut result = self.content.to_string();
        for var in vars {
            result = result.replace(var.placeholder(), &var.value());
        }
        result
    }

    /// Write asset to output directory.
    ///
    /// Returns the relative path to the written file.
    pub fn write_to(&self, output_dir: &Path) -> std::io::Result<PathBuf> {
        let filename = self.filename();
        let path = output_dir.join(&filename);
        std::fs::write(&path, self.content)?;
        Ok(PathBuf::from(filename))
    }

    /// Write asset with template variables to output directory.
    /// Uses rendered content hash for cache-busting when vars change.
    pub fn write_rendered_to(
        &self,
        output_dir: &Path,
        vars: &[TemplateVar],
    ) -> std::io::Result<PathBuf> {
        let filename = self.filename_rendered(vars);
        let path = output_dir.join(&filename);
        fs::write(&path, self.render(vars))?;
        Ok(PathBuf::from(filename))
    }

    /// Clean up old versions of this asset.
    ///
    /// Removes files matching `.{name}-*.{ext}` except current version.
    /// For assets with template variables, pass the same vars used in write_rendered_to
    /// to preserve the correct file.
    pub fn cleanup_old(&self, output_dir: &Path, vars: &[TemplateVar]) -> std::io::Result<()> {
        let current = if vars.is_empty() {
            self.filename()
        } else {
            self.filename_rendered(vars)
        };
        let prefix = format!(".{}-", self.name);
        let suffix = format!(".{}", self.kind.extension());

        for entry in fs::read_dir(output_dir)? {
            let entry = entry?;
            let name = entry.file_name();
            let name_str = name.to_string_lossy();

            if name_str.starts_with(&prefix)
                && name_str.ends_with(&suffix)
                && name_str != current
            {
                fs::remove_file(entry.path())?;
            }
        }

        Ok(())
    }

    /// Generate a `<script>` or `<link>` tag for this asset.
    ///
    /// The tag includes `data-tola-generated` attribute to mark it as
    /// generated by Tola (not user content).
    /// Uses rendered content hash for cache-busting when vars change.
    pub fn html_tag(&self, vars: &[TemplateVar]) -> String {
        let filename = self.filename_rendered(vars);
        match self.kind {
            AssetKind::Css => format!(
                r#"<link rel="stylesheet" href="/{}" {}>"#,
                filename, GENERATED_ATTR
            ),
            AssetKind::JavaScript => format!(
                r#"<script src="/{}" {}></script>"#,
                filename, GENERATED_ATTR
            ),
        }
    }
}

// ============================================================================
// Predefined Assets
// ============================================================================

/// Enhance CSS for SVG theme adaptation and dark mode.
pub const ENHANCE_CSS: EmbeddedAsset = EmbeddedAsset::new(
    AssetKind::Css,
    "enhance",
    include_str!("css/enhance.css"),
);

/// Hot reload runtime JavaScript.
pub const HOTRELOAD_JS: EmbeddedAsset = EmbeddedAsset::new(
    AssetKind::JavaScript,
    "hotreload",
    include_str!("serve/hotreload.js"),
);

// ============================================================================
// HTML Templates (server-side rendered, no hash needed)
// ============================================================================

/// Template variable for HTML template replacement.
#[derive(Debug, Clone)]
pub enum HtmlVar<'a> {
    /// Page title: `{title}`
    Title(&'a str),
    /// Tola version: `{version}`
    Version(&'a str),
    /// Directory path: `{path}`
    Path(&'a str),
    /// Parent directory link: `{parent_link}`
    ParentLink(&'a str),
    /// Directory entries: `{entries}`
    Entries(&'a str),
}

impl HtmlVar<'_> {
    /// Placeholder string in the template.
    pub const fn placeholder(&self) -> &'static str {
        match self {
            Self::Title(_) => "{title}",
            Self::Version(_) => "{version}",
            Self::Path(_) => "{path}",
            Self::ParentLink(_) => "{parent_link}",
            Self::Entries(_) => "{entries}",
        }
    }

    /// Replacement value.
    pub fn value(&self) -> &str {
        match self {
            Self::Title(v)
            | Self::Version(v)
            | Self::Path(v)
            | Self::ParentLink(v)
            | Self::Entries(v) => v,
        }
    }
}

/// An embedded HTML template for server-side rendering.
///
/// Unlike `EmbeddedAsset`, this is for dynamic content returned directly
/// by the server without writing to disk or cache-busting.
pub struct HtmlTemplate {
    content: &'static str,
}

impl HtmlTemplate {
    /// Create a new HTML template.
    pub const fn new(content: &'static str) -> Self {
        Self { content }
    }

    /// Render template with typed variable replacements.
    pub fn render(&self, vars: &[HtmlVar<'_>]) -> String {
        let mut result = self.content.to_string();
        for var in vars {
            result = result.replace(var.placeholder(), var.value());
        }
        result
    }
}

/// Welcome page shown when output directory is empty.
pub const WELCOME_HTML: HtmlTemplate = HtmlTemplate::new(include_str!("serve/welcome.html"));

/// Directory listing page.
pub const DIRECTORY_HTML: HtmlTemplate = HtmlTemplate::new(include_str!("serve/directory.html"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_asset_filename() {
        let filename = ENHANCE_CSS.filename();
        assert!(filename.starts_with(".enhance-"));
        assert!(filename.ends_with(".css"));
    }

    #[test]
    fn test_asset_hash_length() {
        let hash = ENHANCE_CSS.hash();
        assert_eq!(hash.len(), 8);
        assert!(hash.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn test_template_render() {
        let js = EmbeddedAsset::new(
            AssetKind::JavaScript,
            "test",
            "connect(__TOLA_WS_PORT__)",
        );
        let rendered = js.render(&[TemplateVar::WsPort(35729)]);
        assert_eq!(rendered, "connect(35729)");
    }

    #[test]
    fn test_html_tag_css() {
        let tag = ENHANCE_CSS.html_tag();
        assert!(tag.starts_with(r#"<link rel="stylesheet" href="/.enhance-"#));
        assert!(tag.contains("data-tola-generated"));
        assert!(tag.ends_with(r#">"#));
    }

    #[test]
    fn test_html_tag_js() {
        let tag = HOTRELOAD_JS.html_tag();
        assert!(tag.starts_with(r#"<script src="/.hotreload-"#));
        assert!(tag.contains("data-tola-generated"));
        assert!(tag.ends_with(r#"></script>"#));
    }
}
